let _music = {
    "rowLen": 11025,
    "endPattern": 4,
    "songData": [
        {
            "osc1_oct": 5,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 96,
            "osc1_waveform": 2,
            "osc2_oct": 2,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 41,
            "osc2_waveform": 2,
            "noise_fader": 11,
            "env_attack": 59297,
            "env_sustain": 12110,
            "env_release": 154733,
            "env_master": 105,
            "fx_filter": 2,
            "fx_freq": 585,
            "fx_resonance": 104,
            "fx_delay_time": 6,
            "fx_delay_amt": 162,
            "fx_pan_freq": 1,
            "fx_pan_amt": 135,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 7,
            "lfo_amt": 56,
            "lfo_waveform": 0,
            "p": [
                1,
                3,
                4
            ],
            "c": [
                {
                    "n": [
                        183,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        183,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        183,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        180,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        183,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        159,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        183,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 5,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 187,
            "osc1_waveform": 2,
            "osc2_oct": 6,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 115,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 13163,
            "env_sustain": 3426,
            "env_release": 26863,
            "env_master": 255,
            "fx_filter": 2,
            "fx_freq": 696,
            "fx_resonance": 96,
            "fx_delay_time": 8,
            "fx_delay_amt": 41,
            "fx_pan_freq": 4,
            "fx_pan_amt": 159,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 7,
            "lfo_amt": 60,
            "lfo_waveform": 1,
            "p": [
                0,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        183,
                        0,
                        0,
                        0,
                        182,
                        0,
                        0,
                        0,
                        180,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        183,
                        0,
                        0,
                        0,
                        182,
                        0,
                        0,
                        0,
                        178,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "songLen": 34
}
